### ISSUE TITLE
Create minimalistic vignette with short examples of each geom

### ISSUE THREAD

**Issue by VPetukhov** [VPetukhov/ggrastr#2]

**Comment by evanbiederstedt** [comment]
I think this is roughly done as well. Naturally, we could always add more examples to the vignettes. 

I'll close this for now, and we can re-visit as necessary. Feel free to re-open.

**Comment by VPetukhov** [comment]
Do we? The main vignette is not quite minimalistic, and it misses all stuff from the beeswarm and geom_jitter.

**Comment by evanbiederstedt** [comment]
Good point, this needs improvement. I'll re-open, as we could do better. 

(I'm being lazy)

**Comment by evanbiederstedt** [comment]
This PR attempts to solve this: https://github.com/VPetukhov/ggrastr/pull/13
