### ISSUE TITLE
make default dpi configurable through global option

### ISSUE THREAD

**Issue by jan-glx** [VPetukhov/ggrastr#20]
e.g. :
`rasterise <- function (layer, dpi = options("ggrastr.default.dpi"), dev = "cairo") `

**Comment by evanbiederstedt** [comment]
Hi there

We welcome feature requests. Please make a pull request with these changes, and we'll review. 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
Added in the PR above. Thanks @jan-glx !
