### ISSUE TITLE
officially but very softly deprecate` geom_xxx_rast`

### ISSUE THREAD

**Issue by jan-glx** [VPetukhov/ggrastr#22]
In https://github.com/VPetukhov/ggrastr/issues/21#issuecomment-768536566_ @evanbiederstedt  wrote:
> Throwing a warning at this stage after several months feels a bit confusing/pedantic. I worry it will cause more confusion than necessary.

I agree that hard or even [soft deprecation](https://cran.r-project.org/web/packages/lifecycle/vignettes/lifecycle.html) that throws a warning at top-level might cause more harm than good, but you could document it as deprecated (as opposed to the current labeling as equal alternative), I believe that would make the use of `ggraster` easier to learn and teach in the long run.

**Comment by evanbiederstedt** [comment]
Hi @jan-glx 

> you could document it as deprecated (as opposed to the current labeling as equal alternative), I believe that would make the use of ggraster easier to learn and teach in the long run.

Yes, we tried to detail this in the README and the vignettes: https://htmlpreview.github.io/?https://raw.githubusercontent.com/VPetukhov/ggrastr/master/doc/Raster_geoms.html

There might be a better solution for users to clarify that e.g. `geom_xxx_rast` is a historical remnant. 

In terms of learning and teaching, that's definitely something for the vignettes. Please let us know if there's more we could do here.

**Comment by evanbiederstedt** [comment]
It's a nice suggestion, but I think the current setup is the best of all worlds. 

I do see where you're coming from of course. Besides mentioning this in the README and vignettes however, I don't see a better way to "deprecate" in this case. `.Deprecated()` is simply too strong.
