### ISSUE TITLE
Rasterise geom_sf layer

### ISSUE THREAD

**Issue by ericscheier** [VPetukhov/ggrastr#25]
The [vignette](https://htmlpreview.github.io/?https://raw.githubusercontent.com/VPetukhov/ggrastr/master/doc/Raster_geoms.html) states that any ggplot2 layer can be rasterised using the function `rasterise()`.

However, this does not seem to work for [`ggplot2::geom_sf()`](https://ggplot2.tidyverse.org/reference/ggsf.html) layers. A reproducible example is below:

```{r}
library(sf)
library(maps)
world1 <- sf::st_as_sf(maps::map('world', plot = FALSE, fill = TRUE))
library(ggplot2)
ggplot2::ggplot() + ggplot2::geom_sf(data = world1)
```
![image](https://user-images.githubusercontent.com/4824555/109220385-dbb00100-7786-11eb-9905-21f476fd9de3.png)

```{r}
library(ggrastr)
ggplot2::ggplot() + ggrastr::rasterise(ggplot2::geom_sf(data = world1))
```
> Error: Cannot rasterise an object of class `list`. Must be either 'cairo', 'ragg', or 'ragg_png'.
> 2: stop("Cannot rasterise an object of class `", class(layer)[1], 
>       "`. Must be either 'cairo', 'ragg', or 'ragg_png'.", call. = FALSE)
> 1: ggrastr::rasterise(ggplot2::geom_sf(data = world1))

Indeed, by design `geom_sf` returns a list:
```{r}
lapply(ggplot2::geom_sf(data = world1),class)
```
> [[1]]
> [1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"         "gg"           
> 
> [[2]]
> [1] "CoordSf"        "CoordCartesian" "Coord"          "ggproto"         "gg" 

This seems to trip the check in [`rasterise`](https://github.com/VPetukhov/ggrastr/blob/2b8beca40b3796fac5bc5dff5b29f5eb2c15d16b/R/rasterise.R#L30):
```
  if (!inherits(layer, "Layer")) {
    stop("Cannot rasterise an object of class `", class(layer)[1], "`. Must be either 'cairo', 'ragg', or 'ragg_png'.", call. = FALSE)
  }
```
So:
1. Can geom_sf layers be rasterised given that they contain a layer object (or is there a better way to rasterise such data)?
2. Is this error message not a bit misleading since the check indicates that the object must be of class 'Layer', whereas the message seems to refer to the graphics device?

**Comment by evanbiederstedt** [comment]
Hi @ericscheier 

Thanks for the issue. I haven't had time to check things closely yet, so I'll write down some thoughts---I don't know the exact fix yet:

This is really interesting! You're right that this is an edge case we never noticed before. I took a look at the `geoms` here:
https://ggplot2.tidyverse.org/reference/

Virtually all of them follow  the pattern of having a class `"LayerInstance" "Layer"         "ggproto"       "gg"   `
```
> class(geom_ribbon())
[1] "LayerInstance" "Layer"         "ggproto"       "gg"     
```

However, `geom_sf()` is a list, as you mention:

```
> class(geom_sf())
[1] "list"
> lapply(geom_sf(), class)
[[1]]
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           

[[2]]
[1] "CoordSf"        "CoordCartesian" "Coord"          "ggproto"       
[5] "gg"            
```

It appears to be a combination of geom, stat, and coord for simple feature (sf) objects. The labels and text work have the "geom classes" we expect:

```
> class(geom_sf())
[1] "list"
> class(coord_sf())
[1] "CoordSf"        "CoordCartesian" "Coord"          "ggproto"       
[5] "gg"            
> class(geom_sf_label())
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           
> class(geom_sf_text())
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           
> class(stat_sf())
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           
> class(coord_cartesian())
[1] "CoordCartesian" "Coord"          "ggproto"        "gg"   
```

Basically, the current conditional is meant to check whether the following is a [ggproto object](https://ggplot2.tidyverse.org/reference/ggproto.html):

```
# Take geom from input layer
old_geom <- layer$geom
```

e.g. 

```
> geom_sf_label()$geom
<ggproto object: Class GeomLabel, Geom, gg>
    aesthetics: function
    default_aes: uneval
    draw_group: function
    draw_key: function
    draw_layer: function
    draw_panel: function
    extra_params: na.rm
    handle_na: function
    non_missing_aes: 
    optional_aes: 
    parameters: function
    required_aes: x y label
    setup_data: function
    setup_params: function
    use_defaults: function
    super:  <ggproto object: Class Geom, gg>
```

In this case, the closest thing I've seen to a ggproto object appears to be a `Coord`:
```
> coord_sf()
<ggproto object: Class CoordSf, CoordCartesian, Coord, gg>
    aspect: function
    backtransform_range: function
    clip: on
    crs: NULL
    datum: crs
    default: FALSE
    default_crs: crs
    determine_crs: function
    distance: function
    expand: TRUE
    fixup_graticule_labels: function
    get_default_crs: function
    is_free: function
    is_linear: function
    label_axes: list
    label_graticule: 
    labels: function
    limits: list
    lims_method: cross
    modify_scales: function
    ndiscr: 100
    params: list
    range: function
    record_bbox: function
    render_axis_h: function
    render_axis_v: function
    render_bg: function
    render_fg: function
    setup_data: function
    setup_layout: function
    setup_panel_guides: function
    setup_panel_params: function
    setup_params: function
    train_panel_guides: function
    transform: function
    super:  <ggproto object: Class CoordSf, CoordCartesian, Coord, gg>
    ```

This may be the layer we need to access. 

So: 

> 1. Can geom_sf layers be rasterised given that they contain a layer object (or is there a better way to rasterise such data)?

Not sure yet, tbh. The above might be a fix, but we'd have to try it out. 

> 2. Is this error message not a bit misleading since the check indicates that the object must be of class 'Layer', whereas the message seems to refer to the graphics device?

That's reasonable, we could change this. Please feel free to make a pull request as well :)

Naturally, if you fix the issue for `geom_sf()` before us, please make a PR and we'll review/incorporate. 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
Hi @ericscheier 

Thanks for the issue. I haven't had time to check things closely yet, so I'll write down some thoughts---I don't know the exact fix yet. CC @VPetukhov @teunbrand 

This is really interesting! You're right that this is an edge case we never noticed before. I took a look at the `geoms` here:
https://ggplot2.tidyverse.org/reference/

Virtually all of them follow  the pattern of having a class `"LayerInstance" "Layer"         "ggproto"       "gg"   `
```
> class(geom_ribbon())
[1] "LayerInstance" "Layer"         "ggproto"       "gg"     
```

However, `geom_sf()` is a list, as you mention:

```
> class(geom_sf())
[1] "list"
> lapply(geom_sf(), class)
[[1]]
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           

[[2]]
[1] "CoordSf"        "CoordCartesian" "Coord"          "ggproto"       
[5] "gg"            
```

It appears to be a combination of geom, stat, and coord for simple feature (sf) objects. The labels and text work have the "geom classes" we expect:

```
> class(geom_sf())
[1] "list"
> class(coord_sf())
[1] "CoordSf"        "CoordCartesian" "Coord"          "ggproto"       
[5] "gg"            
> class(geom_sf_label())
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           
> class(geom_sf_text())
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           
> class(stat_sf())
[1] "LayerInstance" "LayerSf"       "Layer"         "ggproto"      
[5] "gg"           
> class(coord_cartesian())
[1] "CoordCartesian" "Coord"          "ggproto"        "gg"   
```

Basically, the current conditional is meant to check whether the following is a [ggproto object](https://ggplot2.tidyverse.org/reference/ggproto.html):

```
# Take geom from input layer
old_geom <- layer$geom
```

e.g. 

```
> geom_sf_label()$geom
<ggproto object: Class GeomLabel, Geom, gg>
    aesthetics: function
    default_aes: uneval
    draw_group: function
    draw_key: function
    draw_layer: function
    draw_panel: function
    extra_params: na.rm
    handle_na: function
    non_missing_aes: 
    optional_aes: 
    parameters: function
    required_aes: x y label
    setup_data: function
    setup_params: function
    use_defaults: function
    super:  <ggproto object: Class Geom, gg>
```

In this case, the closest thing I've seen to a ggproto object appears to be a `Coord`:
```
> coord_sf()
<ggproto object: Class CoordSf, CoordCartesian, Coord, gg>
    aspect: function
    backtransform_range: function
    clip: on
    crs: NULL
    datum: crs
    default: FALSE
    default_crs: crs
    determine_crs: function
    distance: function
    expand: TRUE
    fixup_graticule_labels: function
    get_default_crs: function
    is_free: function
    is_linear: function
    label_axes: list
    label_graticule: 
    labels: function
    limits: list
    lims_method: cross
    modify_scales: function
    ndiscr: 100
    params: list
    range: function
    record_bbox: function
    render_axis_h: function
    render_axis_v: function
    render_bg: function
    render_fg: function
    setup_data: function
    setup_layout: function
    setup_panel_guides: function
    setup_panel_params: function
    setup_params: function
    train_panel_guides: function
    transform: function
    super:  <ggproto object: Class CoordSf, CoordCartesian, Coord, gg>
```

This may be the layer we need to access. 

So: 

> 1. Can geom_sf layers be rasterised given that they contain a layer object (or is there a better way to rasterise such data)?

Not sure yet, tbh. The above might be a fix, but we'd have to try it out. 

> 2. Is this error message not a bit misleading since the check indicates that the object must be of class 'Layer', whereas the message seems to refer to the graphics device?

That's reasonable, we could change this. Please feel free to make a pull request as well :)

Naturally, if you fix the issue for `geom_sf()` before us, please make a PR and we'll review/incorporate. 

Thanks, Evan

**Comment by teunbrand** [comment]
Here is a workaround that should work for `geom_sf()` layers.

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(ggrastr)
library(maps)
library(ggplot2)

world1 <- sf::st_as_sf(maps::map('world', plot = FALSE, fill = TRUE))
ggplot2::ggplot() + 
  lapply(ggplot2::geom_sf(data = world1), function(x) {
    if (inherits(x, "LayerInstance")) {
      x <- rasterise(x)
    }
    return(x)
  })
```

![](https://i.imgur.com/L8qwgpN.png)

<sup>Created on 2021-02-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

 Some options for longer term solutions might be:
 
 * Make `rasterise()` an S3 generic and have a list method that recursively scans through lists for `Layer` objects.
 * Explicitly use branch logic in `rasterise()` to catch the `geom_sf()` objects.

**Comment by evanbiederstedt** [comment]
Thanks @teunbrand 

> Explicitly use branch logic in `rasterise()` to catch the `geom_sf() `objects.

This is roughly what I had in mind. I think we could revise `rasterise()` accordingly to catch this. 

> Make rasterise() an S3 generic and have a list method that recursively scans through lists for Layer objects.

I may not fully follow where you're coming from :) I think we could (quickly) modify the current `rasterise()` function.

> The vignette states that any ggplot2 layer can be rasterised using the function rasterise().

The only other behavior I found unexpected looking through the `geoms` [here](https://ggplot2.tidyverse.org/reference/) was `geom_map()`

```
> class(geom_map())
Error in is.data.frame(map) : argument "map" is missing, with no default
```

**Comment by ericscheier** [comment]
Thanks @evanbiederstedt and @teunbrand for looking into this. I can confirm that @teunbrand 's workaround is successful for me as well, and better than (but conceptually similar to) the workaround that I came up with yesterday upon further investigation. Currently, I am using the following function in the spirit of prior ggrastr functions which I am aware are to be deprecated:

```
geom_sf_rast <- function(layer, 
                              dpi = NULL,
                              dev = NULL){
  layer <- lapply(layer, function(x) {
    if (inherits(x, "LayerInstance")) {
      x <- ggrastr::rasterise(x, dpi=dpi,dev=dev)
    }
    return(x)
  })
  return(layer)
}
```

I can look into formalizing this and the checking/error logic changes into a pull request or two next week, but it sounds like there may be other paths that I am less well suited to implement (S3 generic makes conceptual sense to me but I am not skilled enough to do this). Do not let me stand in the way of any progress.

For now, thank you for the workaround and for confirming that this is a real issue instead of user error or system-specific aspects.

**Comment by evanbiederstedt** [comment]
These changes are now in the `develop` branch. We'll push to `master` soon and re-release with 0.2.3 (including releasing on CRAN).
