### ISSUE TITLE
`rasterise` function for ggplot object

### ISSUE THREAD

**Issue by VPetukhov** [VPetukhov/ggrastr#29]
The current [`rasterise`](https://github.com/VPetukhov/ggrastr/blob/d200ef16fad7198c9f69eadc0fd4fa774c34432d/R/rasterise.R#L33) function needs to be applied for individual layers. And it requires using it on the plot construction stage. I just realized that it should be easy to add a function like `rasterise.ggplot(gg, layers=c('Point', 'Tile'))`, which takes an existing plot and replaces all layers of types specified in `layers` with its rasterized versions. In this case, a user can call `rasterise` after the plot is created, so packages would not need to depend on ggrastr at all. For example, in [`sccore::embeddingPlot`](https://github.com/kharchenkolab/sccore/blob/8fd33954622767024524baae31e56210f61786f6/R/plots.R#L412) we could deprecate the rasterization parameters and users would just use `con$plotGraph(...) %>% rasterize(dpi=150)`. There are [four more packages](https://cran.r-project.org/web/packages/ggrastr/index.html) that depend on ggrastr, and I think this functionality would save some effort for their developers, as well.

Not sure if the following implementation works in general case, but at least it does on a couple of examples:
```r
rasterise.gg <- function(gg, layers=c('Point', 'Tile'), ...) {
  gg$layers <- lapply(gg$layers, function(lay) {
    if (length(intersect(class(lay$geom), paste0('Geom', layers))) > 0) rasterize(lay, ...) else lay
  })
  return(gg)
}
```

So we just need to specify that the current `rasterise` is `rasterise.Layer`.

**Comment by evanbiederstedt** [comment]
Yes, we could take advantage of polymorphism here. 

Something like:
```
setGeneric("rasterize", function(input) standardGeneric("rasterize"))
setMethod("rasterize", signature(c("ggplot")), function(input) ... ... ... )
setMethod("rasterize", signature(c("LayerInstance", "Layer", "ggproto")), function(input) ... ... ... ) ## current function
```

As I say, I might take a stab at this later if I get time. CC @VPetukhov

**Comment by VPetukhov** [comment]
Closed in https://github.com/VPetukhov/ggrastr/commit/25b690067d8552f7c9575125922f72ebe62d9b60
