### ISSUE TITLE
Add geom_jitter_rast

### ISSUE THREAD

**Issue by VPetukhov** [VPetukhov/ggrastr#3]
See [geom_jitter](https://ggplot2.tidyverse.org/reference/geom_jitter.html)

**Comment by lutsik** [comment]
+1 for this feature. Any concrete timeplan for it? In any case, thumbs up for the package.

**Comment by VPetukhov** [comment]
Hi! Nope, no real timeplans. You're very welcome to submit a PR though :) It should be similar to [geom-quasirandom-rast](https://github.com/VPetukhov/ggrastr/blob/master/R/geom-quasirandom-rast.R), but using `position_jitter` instead of `position_quasirandom`. Geom `GeomPointRast` can be again re-used here.

**Comment by VPetukhov** [comment]
Closed in https://github.com/VPetukhov/ggrastr/pull/10. So far in the `develop` branch.
