### ISSUE TITLE
Unicode characters in rasterised layer

### ISSUE THREAD

**Issue by jeskowagner** [VPetukhov/ggrastr#32]
Hi!

Thanks for developing ggrastr, it's exactly what I was looking for. I noticed that some unicode characters are not rendered correctly after being rasterised. Here's a minimal example:

```R
library(ggplot2)
library(ggrastr)

df = ggplot2::mpg
p = ggplot(df, aes(x=cty,y=hwy,shape=drv)) +
    geom_point(size=10) + 
    scale_shape_manual(values=c("\u25CF","\u25BA","\u25A0"))
p
```
Which produces the following plot as expected:
![image](https://user-images.githubusercontent.com/35219306/207813439-824abf18-14c2-473a-9794-7ae12529813c.png)

Whereas the following appears to change some unicode characters:
```
rasterise(p)
```
![image](https://user-images.githubusercontent.com/35219306/207813488-a40b87fa-3e2e-4cf3-a158-002a3d73145b.png)

Any idea what might be causing that?

I understand that this issue might not be high priority. For now my workaround has been to embed the points encoded by unicode characters in a non-rasterised layer, but of course that only works if most of your points are rasterised as expected.

**Comment by evanbiederstedt** [comment]
Sorry I missed this earlier

> Any idea what might be causing that?

I don't know sadly. 

I'll put a "Help Wanted" flag up

**Comment by teunbrand** [comment]
Seems to be a device specific issue. `rasterise(p, dev = "ragg")` works just fine.

**Comment by evanbiederstedt** [comment]
I wasn't abled to reproduce myself.

It's possible it was based on an installation of a specific systems library.

**Comment by jeskowagner** [comment]
Interesting, `rasterise(p, dev = "ragg")` indeed solves the issue (same for `ragg_png`). `cairo` however leads to the above issue. As `ragg` works I'll close this, thanks for the help!
