### ISSUE TITLE
File size of rasterized plots

### ISSUE THREAD

**Issue by Zepeng-Mu** [VPetukhov/ggrastr#33]
Hello,

I have a plot where I'am plotting around 30,000 points using rasterize, and I also have some ggplot2 layers like an `abline` and axis titles, but the output PDF is 2.1MB. I feel this is kind of large (especially compared to the png file) and can atcually make things slow if I import it into an editor like inkscape. I wonder whether this is expected and if choosing different plot backend can actually help further reduce the size.

Thanks so much!

**Comment by evanbiederstedt** [comment]
Thanks for using ggrastr 

This sounds expected 

30,000 points is pretty big

If you have reproducible code, we could try to look

Best, Evan

**Comment by Zepeng-Mu** [comment]
Hi, thanks for the reply. I changed dpi from 1500 to 500 and that seemed to reduce the image size to 1/3 and is more manageable now.

**Comment by evanbiederstedt** [comment]
>dpi from 1500 to 500 and that seemed to reduce the image size to 1/3

Ah! I see the issue

Yes, that will indeed change the file size.
