### ISSUE TITLE
geom_segment_raster

### ISSUE THREAD

**Issue by Puriney** [VPetukhov/ggrastr#36]
Hello, I was wondering if there is a chance that you implement the `geom_segment_rast` function? I am a computational biologist doing single-cell genomics. Your package with the function `geom_point_rast` is very popular in the field as it is very helpful in visualizing single-cells at a UMAP/tSNE embedding. I recently realized that it will be very helpful to rasterize the `geom_segment`. See a demo below. This is why I initiate this issue. Many thanks. 

```
  data("iris")
  head(iris)
  emb_a <- as_tibble(iris[, 1:2])
  emb_b <- as_tibble(iris[, 3:4])
  z <- iris[, 5]
  
  emb_a_x <- 'Sepal.Length' 
  emb_a_y <- 'Sepal.Width'
  emb_b_x <- 'Petal.Length'
  emb_b_y <- 'Petal.Width'
  spacing_h <- 0.3
  spacing_v <- 0
  emb_a <- emb_a %>% mutate(across(where(is.numeric), function(x) {scales::rescale(x, to=c(0.1, 1.1))} ))
  emb_b <- emb_b %>% mutate(across(where(is.numeric), function(x) {scales::rescale(x, to=c(0.1, 1.1))} ))
  if (spacing_h > 0) {
  emb_b[, emb_b_x] <- emb_b[, emb_b_x] + diff(range(emb_a[, emb_a_x])) + spacing_h
  }
  if (spacing_v > 0) {
  emb_b[, emb_b_y] <- emb_b[, emb_b_y] + diff(range(emb_a[, emb_a_y])) + spacing_v
  }
  
  df <- cbind(emb_a, emb_b, z)
  
  ggplot() +
    geom_point_rast(
      data=df, aes_string(x=emb_a_x, y=emb_a_y, color='z')) + 
    geom_point_rast(
      data=df, aes_string(x=emb_b_x, y=emb_b_y, color='z')) + 
    coord_equal() + 
    theme_void() +
    geom_rect(aes(xmin=min(emb_a[, emb_a_x])-0.1,
                  xmax=max(emb_a[, emb_a_x])+0.1,
                  ymin=min(emb_a[, emb_a_y])-0.1,
                  ymax=max(emb_a[, emb_a_y])+0.1), 
              fill=NA, color='black'
    ) +
    geom_rect(aes(xmin=min(emb_b[, emb_b_x])-0.1,
                  xmax=max(emb_b[, emb_b_x])+0.1,
                  ymin=min(emb_b[, emb_b_y])-0.1,
                  ymax=max(emb_b[, emb_b_y])+0.1), 
              fill=NA, color='black'
    ) +
    geom_segment(
      data = df, 
      aes_string(x=emb_a_x, y=emb_a_y,
                 xend=emb_b_x, yend=emb_b_y,
                 color='z'), alpha=0.5, lwd=0.1)
```

<img width="1164" alt="image" src="https://github.com/VPetukhov/ggrastr/assets/1233372/bec013a1-2d50-4324-a075-31a6e8916176">

**Comment by evanbiederstedt** [comment]
Hi @Puriney 

Thanks for the issue. 

Given the current version of the package, users can rasterize any method:
https://github.com/VPetukhov/ggrastr/blob/main/vignettes/Raster_geoms.md

See the function `rasterize()` or `rasterise()`: https://cran.rstudio.com/web/packages/ggrastr/ggrastr.pdf

We don't really implement individual `geom_*` objects anymore; these functions are nice, but sort of relics from an earlier version of the package. With `rasterize()`, all of these individual methods were made moot; the same logic applies to your request. 

Thanks for using the package

Best, Evan

**Comment by Puriney** [comment]
Oh, it is just in the README. Appreciate for the information. Thanks a lot.
