### ISSUE TITLE
Create release for conda-forge

### ISSUE THREAD

**Issue by scottgigante** [VPetukhov/ggrastr#5]
I'd like to put a recipe to install ggrastr on conda-forge - for this I need a release tarball. Would you be willing to create a release? Thanks!

**Comment by PertuyF** [comment]
Another solution would be to use git tags (named commits) to label a version. But a release tarball would be great.

**Comment by VPetukhov** [comment]
Sorry for not responding on the first comment. I added version tag and uploaded tarball: http://pklab.med.harvard.edu/viktor/ggrastr/ggrastr_0.1.7.tar.gz

**Comment by PertuyF** [comment]
Still going for the recipe @scottgigante ?

**Comment by scottgigante** [comment]
Ah I forgot about this. I think I found an alternative solution at the time.
