### ISSUE TITLE
Upload to CRAN

### ISSUE THREAD

**Issue by rargelaguet** [VPetukhov/ggrastr#6]
I would like to include the ggrastr function to a visualisation package that I am working on. To import the method properly it would be very convenient if it is uploaded as package to CRAN. 

Thank you,
Ricard.

**Comment by rargelaguet** [comment]
Is this going to happen soon? Otherwise I will have to copy paste the source code to my package to be able to use the ggrastr function (I will of course clarify that you are the author)

**Comment by VPetukhov** [comment]
Don't have time for that, sorry. Feel free to take any part of the code. Why don't you use devtools dependency though?

**Comment by LustigePerson** [comment]
I just saw that the package seems to be on CRAN, however in version 0.1.8 which does not seem to exist here in Github.
https://cran.r-project.org/web/packages/ggrastr/index.html

**Comment by evanbiederstedt** [comment]
Hi @LustigePerson 

Yes, I'm updating this shortly---it was only recently uploaded to CRAN. I should be able to update this github repo soon. 

Thanks for the patience, Evan

**Comment by evanbiederstedt** [comment]
I think this is sorted now. I'll continue to make releases here. 

Huzzah, we're on CRAN!

Thanks, Evan
