### ISSUE TITLE
Add this package to ggplot2-exts

### ISSUE THREAD

**Issue by Bisaloo** [VPetukhov/ggrastr#7]
https://www.ggplot2-exts.org/gallery/

It would be super useful for people to discover this great package (and also for those who already know it but forgot its name).

https://github.com/ggplot2-exts/gallery#adding-a-ggplot2-extension

**Comment by VPetukhov** [comment]
I had this task in my list for so long... Thanks for pushing me! Here is the [PR](https://github.com/ggplot2-exts/gallery/pull/80)

**Comment by VPetukhov** [comment]
And so it's merged.
