### ISSUE TITLE
Add geom_violin_rast

### ISSUE THREAD

**Issue by VPetukhov** [VPetukhov/ggrastr#8]

**Comment by evanbiederstedt** [comment]
@VPetukhov 
I was having a look at this issue. 
Could you detail the rationale behind this feature a bit more? 

The strength of ggrastr would be for plots with many many dots. It seems like most people would use `geom_dotplot()` or `geom_jitter()` along with the violin plots, no?

**Comment by VPetukhov** [comment]
@evanbiederstedt,
This task is not a priority by any means, but there are Violin Maps, which takes a lot of space if stored in vector format. See an example [here](https://github.com/khodosevichlab/CellAnnotatoR/blob/master/vignettes/mca_qc.md#more-detailed-qc) under the `plotMarkerListViolinMap` call.

**Comment by evanbiederstedt** [comment]
Hi @VPetukhov 

> which takes a lot of space if stored in vector format

I hadn't considered this---I see why this is a useful feature now. Thanks

**Comment by evanbiederstedt** [comment]
Should be resolved here: https://github.com/VPetukhov/ggrastr/pull/19

Will version and release on master soon
